Load boxes for users
PEM-Humboldt/ipt pull request #14
Opened 2021-07-08 03:12 UTC by alegnaaived

2021-07-08 13:21 UTC, Trjegul84 requested changes

2021-07-08 13:21 UTC, Trjegul84 commented on src/main/webapp/WEB-INF/pages/admin/user.ftl
>                              selectableHeader: "<div class='custom-header'><@s.text name="admin.user.restrictedResources" /></div>",
Parece que este div debe ser el padre del div class="ms-selectable y no al revés por eso se ve el titulo de cada casilla por fuera y no dentro de cada casilla. Talvez eso esta en desorden y por eso no carga los usuarios. Lo que debemos lograr es que el script funcione y cargue los usuarios y eso no esta sucendiendo.

![Screenshot_20210708_075503](https://user-images.githubusercontent.com/72577339/124928245-1479a580-dfc5-11eb-8aab-bcab10eac117.png)

Revisemos el div padre de ceiba original esta asi:

![Screenshot_20210708_081320](https://user-images.githubusercontent.com/72577339/124928520-47239e00-dfc5-11eb-971b-2794944582af.png)

2021-07-23 22:06 UTC, Trjegul84 requested changes
No me funciona la interfaz de los cuadritos para seleccionar recursos. 
No sale nada y se debe cambiar este código para que no aparezca en la interfaz

admin.user.restrictedResourcesadmin.user.grantAccessTo

![Screenshot_20210723_170132](https://user-images.githubusercontent.com/72577339/126845871-7aee0c11-878c-4f8c-b882-1fa377249312.png)

También los nombres de los botones.

2021-07-26 20:55 UTC, alegnaaived commented
> No me funciona la interfaz de los cuadritos para seleccionar recursos.
> No sale nada y se debe cambiar este código para que no aparezca en la interfaz
> 
> admin.user.restrictedResourcesadmin.user.grantAccessTo
> 
> ![Screenshot_20210723_170132](https://user-images.githubusercontent.com/72577339/126845871-7aee0c11-878c-4f8c-b882-1fa377249312.png)
> 
> También los nombres de los botones.

¿Probaste viendo el contenido en español? Prueba por favor un usuario que no sea @humboldt para ver si te sale recursos disponibles a asignar o si no.

2021-07-29 19:25 UTC, Trjegul84 approved these changes

2021-07-29 19:25 UTC, merged