Feature/commit10
PEM-Humboldt/ipt pull request #7
Opened 2021-06-21 03:56 UTC by alegnaaived

I would like to test these changes against resources. I would prefer to validate those functionalities with I2D team

2021-06-21 08:56 UTC, timrobertson100 commented
At GBIF we've just become aware of this fork. It looks like you are following changes for the 2.5.x work (thank you) but it also looks like there may be things here we should consider pushing upstream into gbif/ipt to make your lives easier.

If so, can you please open individual issues on gbif/ipt for features, or corrections to translations so we can track them? If there are styling hooks we can add that make it easier for you, please also open an issue.

Please let us know what we can do to help you.

CC @mike-podolskiy90 (now IPT lead dev at GBIF) and @MattBlissett for info

2021-06-21 17:47 UTC, Trjegul84 commented
> At GBIF we've just become aware of this fork. It looks like you are following changes for the 2.5.x work (thank you) but it also looks like there may be things here we should consider pushing upstream into gbif/ipt to make your lives easier.
> 
> If so, can you please open individual issues on gbif/ipt for features, or corrections to translations so we can track them? If there are styling hooks we can add that make it easier for you, please also open an issue.
> 
> Please let us know what we can do to help you.
> 
> CC @mike-podolskiy90 (now IPT lead dev at GBIF) and @MattBlissett for info

Dear Tim, thank you for your comment. We would like to inform you that we are just creating our own ipt adapted to the needs of our entity, by mistake we have sent pull request to the ipt master branch but it was not our initial intention. We are going to initiate changes in .java files in case we need help we will be contacting you. Thank you very much.

2021-06-21 18:27 UTC, Trjegul84 requested changes
Changes of 
src/main/webapp/WEB-INF/pages/inc/header.ftl
src/main/webapp/WEB-INF/pages/inc/menu.ftl
src/main/webapp/images/logo-IAvH.png
src/main/webapp/styles/main.css

Also change in title are duplicated in src/main/resources/ApplicationResources_es.properties and es.properties and were implemented in commit9. Please do not duplicate the work.
Where implemented in the commit9 already merged. 
In this commit are missing the changes for:
 - src/main/webapp/WEB-INF/pages/portal/resource.ftl
 - src/main/webapp/WEB-INF/pages/manage/eml/additional.ftl (What if this not exists? is its Creation needed ?)
 also  the files following files are still missing
 src/main/webapp/js/jquery.multi-select.js
 src/main/webapp/styles/jquery/multi-select.css
And the image src/main/webapp/styles/images/switch.png
Please delete the repetead changes of commit9 and finish the commit 10 or specify why these were not implemented.

2021-06-25 16:58 UTC, Trjegul84 approved these changes

2021-06-25 16:58 UTC, merged